Algoritmo "Menor número"
//Programa que diz qual número é o menor dentre 3
//11º pseudocódigo
Var

  p,s,t, menor: real

Inicio

  escreva ("Digite o primeiro número: ")
  leia (p)
  escreva ("Digite o segundo número: ")
  leia (s)
  escreva ("Digite o terceiro número: ")
  leia (t)
  
   se (p<s) e (p<t) entao
     escreva ("O menor valor é: ", p)
  senao
   se  (s<t) entao
     escreva ("O menor valor é: ", s)
  senao
     escreva ("O menor valor é: ", t)
   fimse
   fimse


Fimalgoritmo