algoritmo "Soma_enquanto"
//Programa que soma os números até que seja digitado o numeral 0
//23º pseudocódigo
var

 y,soma: real
 

inicio
  escreva ("Digite o numeral 0 para encerrar o programa")
  escreval
  escreva ("Digite um número: ")
  leia (y)
  
  

  soma <- 0
  enquanto y<>0 faca
   soma <- soma + y
    escreva ("Digite outro número: ")
     leia (y)
      fimenquanto
       escreva ("O valor de todos os y é de: ", soma)

fimalgoritmo